fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.19.0"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.1.0"
    yumrepo_core:
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      ref: "1.0.3"
  symlinks:
    fluentd: "#{source_dir}"
